version: '2'

services:
  ecstore:
    image: 'wykrisdev/shopex-docker:php72-swooleloader'
    container_name: bbc-base
    ports:
      - 80:80
    volumes:
      - .:/data/httpd
    links:
      - mysql
      - redis
      # - ftp
    environment:
      - WEBROOT=/data/httpd
    networks:
      - bbc

  redis:
    image: redis
    hostname: redis
    container_name: bbc-redis
    ports:
      - "6379:6379"
    volumes:
      - ./storage/redis:/data
    networks:
      - bbc

  mysql:
    image: mysql:5.6
    hostname: mysql
    container_name: bbc-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./storage/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - bbc

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   ports:
  #     - "8004:80"
  #   links:
  #     - mysql
  #   environment:
  #     - PMA_HOST=mysql
  #   networks:
  #     - bbc

#   ftp:
#     image: bogem/ftp
#     hostname: ftp
#     environment:
#       - FTP_USER=ftp
#       - FTP_PASS=ftp
#       - PASV_ADDRESS=0.0.0.0
#     volumes:
#       - ./storage/ftp:/home/vsftpd
#     ports:
#       - "20:20"
#       - "21:21"
# #      - "47400-47470:47400-47470"
#     networks:
#        - bbc

networks:
  bbc:
    driver: bridge
