version: '2'

services:
  ecstore:
    image: 'wykrisdev/shopex-docker:php56-swooleloader-mysql'
    ports:
      - 8006:80
    volumes:
      #本地路径/远程路径
      - ${coderoot}:/data/httpd
    links:
      - mysql
      #- ftp
      # - redis
    environment:
      #默认web的路径
      - WEBROOT="${webroot}"
      #默认zl文件的路径
      - LICENSE_PATH="${license_path}"
    networks:
      - ecstore

  # redis:
  #   image: redis
  #   hostname: redis
  #   ports:
  #     - "8379:6379"
  #   volumes:
  #     - ${storage_path}/redis:/data
  #   networks:
  #     - ecstore

  mysql:
    image: mysql:5.6
    hostname: mysql
    ports:
      - "3306:3306"
    volumes:
      - ${storage_path}/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - ecstore

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8004:80"
    links:
      - mysql
    environment:
      - PMA_HOST=mysql
    networks:
      - ecstore

#   ftp:
#     image: bogem/ftp
#     hostname: ftp
#     environment:
#       - FTP_USER=ftp
#       - FTP_PASS=ftp
#       - PASV_ADDRESS=0.0.0.0
#     volumes:
#       - ${storage_path}/ftp:/home/vsftpd
#     ports:
#       - "20:20"
#       - "21:21"
# #      - "47400-47470:47400-47470"
#     networks:
#        - ecstore

networks:
  ecstore:
    driver: bridge
